In [ ]:
import torch
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [ ]:
query = inputs[1]
attnscores = torch.empty(inputs.shape[0])
for i,x_i in enumerate(inputs):
  attnscores[i] = torch.dot(query, x_i)

print(attnscores)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [ ]:
res = 0
for i,item in enumerate(inputs[0]):
  res += inputs[0][i] * query[i]
  print(inputs[0][i], "*", query[i])
print(res)
print(torch.dot(inputs[0], query))

tensor(0.4300) * tensor(0.5500)
tensor(0.1500) * tensor(0.8700)
tensor(0.8900) * tensor(0.6600)
tensor(0.9544)
tensor(0.9544)


In [ ]:
#normalize
attweights = attnscores / attnscores.sum()
print(attweights)
print(attweights.sum())

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
tensor(1.0000)


In [ ]:
def softmax_n(x):
  return torch.exp(x) / torch.exp(x).sum(dim=0)

attweightsn = softmax_n(attnscores)
print(attweightsn)
print(attweightsn.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [ ]:
# softmax for normalization, handle extreme values and good gradient
atteweights2 = torch.softmax(attnscores, dim=0)
print(atteweights2)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])


In [ ]:
query = inputs[1]
contextvec2 = torch.zeros(query.shape)
print(contextvec2)
for i, xi in enumerate(inputs):
  contextvec2 += atteweights2[i]*xi
  print(atteweights2[i], "*", xi)

print(contextvec2)

tensor([0., 0., 0.])
tensor(0.1385) * tensor([0.4300, 0.1500, 0.8900])
tensor(0.2379) * tensor([0.5500, 0.8700, 0.6600])
tensor(0.2333) * tensor([0.5700, 0.8500, 0.6400])
tensor(0.1240) * tensor([0.2200, 0.5800, 0.3300])
tensor(0.1082) * tensor([0.7700, 0.2500, 0.1000])
tensor(0.1581) * tensor([0.0500, 0.8000, 0.5500])
tensor([0.4419, 0.6515, 0.5683])


In [ ]:
attenScores = torch.empty(6,6)
for i,xi in enumerate(inputs):
  for j,xj in enumerate(inputs):
    attenScores[i,j] = torch.dot(xi, xj)
    print(xi, "*", xj)

tensor([0.4300, 0.1500, 0.8900]) * tensor([0.4300, 0.1500, 0.8900])
tensor([0.4300, 0.1500, 0.8900]) * tensor([0.5500, 0.8700, 0.6600])
tensor([0.4300, 0.1500, 0.8900]) * tensor([0.5700, 0.8500, 0.6400])
tensor([0.4300, 0.1500, 0.8900]) * tensor([0.2200, 0.5800, 0.3300])
tensor([0.4300, 0.1500, 0.8900]) * tensor([0.7700, 0.2500, 0.1000])
tensor([0.4300, 0.1500, 0.8900]) * tensor([0.0500, 0.8000, 0.5500])
tensor([0.5500, 0.8700, 0.6600]) * tensor([0.4300, 0.1500, 0.8900])
tensor([0.5500, 0.8700, 0.6600]) * tensor([0.5500, 0.8700, 0.6600])
tensor([0.5500, 0.8700, 0.6600]) * tensor([0.5700, 0.8500, 0.6400])
tensor([0.5500, 0.8700, 0.6600]) * tensor([0.2200, 0.5800, 0.3300])
tensor([0.5500, 0.8700, 0.6600]) * tensor([0.7700, 0.2500, 0.1000])
tensor([0.5500, 0.8700, 0.6600]) * tensor([0.0500, 0.8000, 0.5500])
tensor([0.5700, 0.8500, 0.6400]) * tensor([0.4300, 0.1500, 0.8900])
tensor([0.5700, 0.8500, 0.6400]) * tensor([0.5500, 0.8700, 0.6600])
tensor([0.5700, 0.8500, 0.6400]) * tensor([0.570

In [ ]:
print(attenScores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [ ]:
x = torch.tensor([[1,2], [3,4], [0, 3]])
y = torch.tensor([[1,1,1], [0,0,1]])
print(torch.sum(x, dim=-1)) #row sum
print(torch.sum(x, dim=1))
print(torch.sum(x, dim=0))
print(x @ y)

tensor([3, 7, 3])
tensor([3, 7, 3])
tensor([4, 9])
tensor([[1, 1, 3],
        [3, 3, 7],
        [0, 0, 3]])


In [ ]:
attenWeights = torch.softmax(attenScores, dim=-1)
print(attenWeights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [ ]:
print(attenWeights[1].sum(dim=-1))

tensor(1.)


In [ ]:
contextVectors = attenWeights @ inputs
print(contextVectors)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


In [ ]:
contextVectors = torch.matmul(attenWeights, inputs)
print(contextVectors)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


In [ ]:
x2 = inputs[1]
din = inputs.shape[1]
dout = 2

torch.manual_seed(1)
queryW = torch.nn.Parameter(torch.rand(din, dout), requires_grad=False)
keyW = torch.nn.Parameter(torch.rand(din, dout), requires_grad=False)
valueW = torch.nn.Parameter(torch.rand(din, dout), requires_grad=False)

In [ ]:
q2 = x2 @ queryW
k2 = x2 @ keyW
v2 = x2 @ valueW
print(q2)
print(k2)
print(v2)

tensor([0.7867, 1.3207])
tensor([1.1354, 1.1429])
tensor([1.1566, 0.8924])


In [ ]:
keys = inputs @ keyW
values = inputs @ valueW
print(keys)
print(values)

tensor([[0.8246, 0.8571],
        [1.1354, 1.1429],
        [1.1192, 1.1387],
        [0.6284, 0.5936],
        [0.5120, 0.7430],
        [0.8267, 0.6773]])
tensor([[0.8726, 0.6427],
        [1.1566, 0.8924],
        [1.1495, 0.8794],
        [0.6079, 0.4954],
        [0.6987, 0.3985],
        [0.7198, 0.6531]])


In [ ]:
keys2 = keys[1]
print(keys2)
attscore22 = q2.dot(keys2)
print(attscore22)

tensor([1.1354, 1.1429])
tensor(2.4027)


In [ ]:
# all att scores for the query q2
attScores2 = q2 @ keys.T
print(attScores2)

tensor([1.7808, 2.4027, 2.3844, 1.2784, 1.3841, 1.5449])


 **Scaled-dot product attention**:
 The reason for the normalization by the embedding dimension size is to
 improve the training performance by avoiding small gradients. For instance,
 when scaling up the embedding dimension, which is typically greater than
 thousand for GPT-like LLMs, large dot products can result in very small
 gradients during backpropagation due to the softmax function applied to
 them. As dot products increase, the softmax function behaves more like a
 step function, resulting in gradients nearing zero. These small gradients can
 drastically slow down learning or cause training to stagnate.

In [ ]:
dk = keys.shape[1]
attenWeights2 = torch.softmax(attScores2 / torch.sqrt(torch.tensor(dk)), dim=-1)
attenWeights2_ = torch.softmax(attScores2 / dk**0.5, dim=-1)
print(attenWeights2)
print(attenWeights2_)

tensor([0.1566, 0.2430, 0.2399, 0.1097, 0.1183, 0.1325])
tensor([0.1566, 0.2430, 0.2399, 0.1097, 0.1183, 0.1325])


In [ ]:
#context vector for q2
contextVectors2 = attenWeights2 @ values
print(contextVectors2)

tensor([0.9382, 0.7165])


# Self Attention

In [10]:
import torch
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [ ]:
import torch
import torch.nn as nn
class SelfAttention(nn.Module):
  def __init__(self, din, dout):
    super().__init__()
    self.queryW = nn.Parameter(torch.rand(din, dout)) #, requires_grad=True
    self.keyW = nn.Parameter(torch.rand(din, dout))
    self.valueW = nn.Parameter(torch.rand(din, dout))

  def forward(self, x):
    keys = x @ self.keyW
    values = x @ self.valueW
    queries = x @ self.queryW
    attScores = queries @ keys.T
    attenWeights = torch.softmax(attScores / keys.shape[1]**0.5, dim = -1) # row ops
    contextVectors = attenWeights @ values
    return contextVectors

torch.manual_seed(1)
selfatt = SelfAttention(3, 2)
print(selfatt(inputs))


tensor([[0.9128, 0.6959],
        [0.9382, 0.7165],
        [0.9376, 0.7161],
        [0.9062, 0.6910],
        [0.9063, 0.6924],
        [0.9149, 0.6973]], grad_fn=<MmBackward0>)


In [ ]:
import torch.nn as nn
a = nn.Linear(3,2)(inputs)
print(a)


tensor([[-0.1324, -0.3585],
        [ 0.1070, -0.4127],
        [ 0.1178, -0.4128],
        [-0.0407, -0.1874],
        [ 0.2270, -0.2899],
        [-0.1343, -0.2042]], grad_fn=<AddmmBackward0>)


In [ ]:
class SelfAttentionV2(nn.Module):
  def __init__(self, din, dout, bias=False):
    super().__init__()
    self.queryW = nn.Linear(din, dout, bias)
    self.keyW = nn.Linear(din, dout, bias)
    self.valueW = nn.Linear(din, dout, bias)

  def forward(self, x):
    keys = self.keyW(x)
    values = self.valueW(x)
    queries = self.queryW(x)
    attScores = queries @ keys.T
    attenWeights = torch.softmax(attScores / keys.shape[-1]**0.5, dim=-1)
    contextVectors = attenWeights @ values
    return contextVectors

torch.manual_seed(1)
selfatt = SelfAttentionV2(3, 2)
print(selfatt(inputs))


tensor([[-0.0636,  0.0255],
        [-0.0612,  0.0248],
        [-0.0613,  0.0248],
        [-0.0611,  0.0247],
        [-0.0639,  0.0256],
        [-0.0599,  0.0244]], grad_fn=<MmBackward0>)


# Causal Attention Mask
only consider the previous and current inputs in a sequence

In [ ]:
queries = selfatt.queryW(inputs)
keys = selfatt.keyW(inputs)
attScores = queries @ keys.T
print(attScores)

tensor([[ 0.0059,  0.0385,  0.0368,  0.0281, -0.0039,  0.0454],
        [-0.0103, -0.0435, -0.0417, -0.0308,  0.0024, -0.0494],
        [-0.0093, -0.0391, -0.0375, -0.0277,  0.0022, -0.0445],
        [-0.0104, -0.0459, -0.0440, -0.0326,  0.0028, -0.0524],
        [ 0.0120,  0.0503,  0.0482,  0.0356, -0.0028,  0.0572],
        [-0.0205, -0.0885, -0.0848, -0.0628,  0.0052, -0.1008]],
       grad_fn=<MmBackward0>)


In [ ]:
attWeights = torch.softmax(attScores / keys.shape[-1]**0.5, dim=-1)
print(attWeights)

tensor([[0.1644, 0.1682, 0.1680, 0.1670, 0.1633, 0.1691],
        [0.1689, 0.1649, 0.1652, 0.1664, 0.1704, 0.1642],
        [0.1686, 0.1651, 0.1653, 0.1665, 0.1700, 0.1645],
        [0.1690, 0.1648, 0.1651, 0.1664, 0.1706, 0.1641],
        [0.1641, 0.1686, 0.1684, 0.1669, 0.1624, 0.1695],
        [0.1712, 0.1631, 0.1636, 0.1661, 0.1743, 0.1617]],
       grad_fn=<SoftmaxBackward0>)


In [ ]:
contsize = attWeights.shape[0]
mask1 = torch.tril(torch.ones(contsize, contsize))
print(mask1)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [ ]:
maskedWeights1 = mask1 * attWeights
print(maskedWeights1)

tensor([[0.1644, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1689, 0.1649, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1686, 0.1651, 0.1653, 0.0000, 0.0000, 0.0000],
        [0.1690, 0.1648, 0.1651, 0.1664, 0.0000, 0.0000],
        [0.1641, 0.1686, 0.1684, 0.1669, 0.1624, 0.0000],
        [0.1712, 0.1631, 0.1636, 0.1661, 0.1743, 0.1617]],
       grad_fn=<MulBackward0>)


In [ ]:
# norm above maskedWeights1
rowSum = maskedWeights1.sum(dim=-1, keepdim=True)
normWeights1 = maskedWeights1 / rowSum
print(normWeights1)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5059, 0.4941, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3379, 0.3309, 0.3312, 0.0000, 0.0000, 0.0000],
        [0.2541, 0.2478, 0.2481, 0.2501, 0.0000, 0.0000],
        [0.1976, 0.2031, 0.2028, 0.2010, 0.1956, 0.0000],
        [0.1712, 0.1631, 0.1636, 0.1661, 0.1743, 0.1617]],
       grad_fn=<DivBackward0>)


In [ ]:
mask2 = torch.triu(torch.ones(contsize, contsize), diagonal=1)
print(mask2)
print(mask2.bool())

tensor([[0., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[False,  True,  True,  True,  True,  True],
        [False, False,  True,  True,  True,  True],
        [False, False, False,  True,  True,  True],
        [False, False, False, False,  True,  True],
        [False, False, False, False, False,  True],
        [False, False, False, False, False, False]])


In [ ]:
masked2 = attScores.masked_fill(mask2.bool(), float('-inf'))
print(masked2)

tensor([[ 0.0059,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-0.0103, -0.0435,    -inf,    -inf,    -inf,    -inf],
        [-0.0093, -0.0391, -0.0375,    -inf,    -inf,    -inf],
        [-0.0104, -0.0459, -0.0440, -0.0326,    -inf,    -inf],
        [ 0.0120,  0.0503,  0.0482,  0.0356, -0.0028,    -inf],
        [-0.0205, -0.0885, -0.0848, -0.0628,  0.0052, -0.1008]],
       grad_fn=<MaskedFillBackward0>)


In [ ]:
attWeights2 = torch.softmax(masked2 / keys.shape[-1]**0.5, dim=-1)
print(attWeights2)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5059, 0.4941, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3379, 0.3309, 0.3312, 0.0000, 0.0000, 0.0000],
        [0.2541, 0.2478, 0.2481, 0.2501, 0.0000, 0.0000],
        [0.1976, 0.2031, 0.2028, 0.2010, 0.1956, 0.0000],
        [0.1712, 0.1631, 0.1636, 0.1661, 0.1743, 0.1617]],
       grad_fn=<SoftmaxBackward0>)


Add dropout: reduce overfitting during training

In [ ]:
torch.manual_seed(1)
dropout = torch.nn.Dropout(0.5)
print(dropout(attWeights2))

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.9883, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.6758, 0.0000, 0.6625, 0.0000, 0.0000, 0.0000],
        [0.5081, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3953, 0.0000, 0.4055, 0.4019, 0.0000, 0.0000],
        [0.3423, 0.0000, 0.0000, 0.0000, 0.3486, 0.0000]],
       grad_fn=<MulBackward0>)


In [11]:
# support to handle batch
batch = torch.stack((inputs, inputs), dim=0)
print(batch)
print(batch.shape)

tensor([[[0.4300, 0.1500, 0.8900],
         [0.5500, 0.8700, 0.6600],
         [0.5700, 0.8500, 0.6400],
         [0.2200, 0.5800, 0.3300],
         [0.7700, 0.2500, 0.1000],
         [0.0500, 0.8000, 0.5500]],

        [[0.4300, 0.1500, 0.8900],
         [0.5500, 0.8700, 0.6600],
         [0.5700, 0.8500, 0.6400],
         [0.2200, 0.5800, 0.3300],
         [0.7700, 0.2500, 0.1000],
         [0.0500, 0.8000, 0.5500]]])
torch.Size([2, 6, 3])


In [ ]:
test = batch.transpose(0,1)
print(test)
print(test.shape)

tensor([[[0.4300, 0.1500, 0.8900],
         [0.4300, 0.1500, 0.8900]],

        [[0.5500, 0.8700, 0.6600],
         [0.5500, 0.8700, 0.6600]],

        [[0.5700, 0.8500, 0.6400],
         [0.5700, 0.8500, 0.6400]],

        [[0.2200, 0.5800, 0.3300],
         [0.2200, 0.5800, 0.3300]],

        [[0.7700, 0.2500, 0.1000],
         [0.7700, 0.2500, 0.1000]],

        [[0.0500, 0.8000, 0.5500],
         [0.0500, 0.8000, 0.5500]]])
torch.Size([6, 2, 3])


In [10]:
import torch.nn as nn
class CausalAttention(nn.Module):
  def __init__(self, din, dout, contextlen, dropout, bias=False):
    super().__init__()
    self.queryW = nn.Linear(din, dout, bias)
    self.keyW = nn.Linear(din, dout, bias)
    self.valueW = nn.Linear(din, dout, bias)
    self.dropout = nn.Dropout(dropout)
    # Registers the resulting mask as a buffer in the module,
    # which means it will be part of the model's state but not updated during training.
    self.register_buffer('mask', torch.triu(torch.ones(contextlen, contextlen), diagonal=1))

  def forward(self, x):
    batchsize, numTokens, din = x.shape
    keys = self.keyW(x)
    values = self.valueW(x)
    queries = self.queryW(x)

    # print("queries", queries)
    attScores = queries @ keys.transpose(1, 2)
    maskedScores = attScores.masked_fill(self.mask.bool()[:numTokens, :numTokens], float('-inf'))
    #print("maskedScores", maskedScores)
    attWeights = torch.softmax(maskedScores / keys.shape[-1]**0.5, dim = -1)
    #print("attWeights", attWeights)
    attWeights = self.dropout(attWeights)

    contextVectors = attWeights @ values
    return contextVectors

torch.manual_seed(1)
contextlen = batch.shape[1]
causalatt = CausalAttention(3, 2, contextlen, 0.5)
print(causalatt(batch))




# 2*6*2 2*2*6=>2*6*6

tensor([[[ 3.8918e-02, -2.3701e-02],
         [-8.6604e-02,  3.0205e-02],
         [ 0.0000e+00,  0.0000e+00],
         [-1.4104e-01,  5.3173e-02],
         [-4.3205e-02,  2.4384e-02],
         [-1.2025e-01,  4.1513e-02]],

        [[ 3.8918e-02, -2.3701e-02],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 9.8875e-03, -6.0214e-03],
         [ 1.2406e-04,  8.6702e-03],
         [-2.5394e-02,  9.0371e-03]]], grad_fn=<UnsafeViewBackward0>)


# Multi-head Attention
run the attention mechanism multiple times (in parallel) with different, learned linear projections. This allows the model to jointly attend to information from different representation subspaces at different positions

In [11]:
temp = torch.cat([batch, causalatt(batch)], dim=-1)
print(temp)

tensor([[[ 0.4300,  0.1500,  0.8900,  0.0000,  0.0000],
         [ 0.5500,  0.8700,  0.6600,  0.0000,  0.0000],
         [ 0.5700,  0.8500,  0.6400, -0.1361,  0.0548],
         [ 0.2200,  0.5800,  0.3300, -0.0387,  0.0138],
         [ 0.7700,  0.2500,  0.1000, -0.0360,  0.0127],
         [ 0.0500,  0.8000,  0.5500, -0.0930,  0.0350]],

        [[ 0.4300,  0.1500,  0.8900,  0.0000,  0.0000],
         [ 0.5500,  0.8700,  0.6600,  0.0197, -0.0120],
         [ 0.5700,  0.8500,  0.6400, -0.1361,  0.0548],
         [ 0.2200,  0.5800,  0.3300,  0.0099, -0.0060],
         [ 0.7700,  0.2500,  0.1000, -0.0393,  0.0233],
         [ 0.0500,  0.8000,  0.5500, -0.0254,  0.0090]]],
       grad_fn=<CatBackward0>)


In [13]:
class MultiHeadAttention(nn.Module):
  def __init__(self, numheads, din, dout, contextlen, dropout, bias=False):
    super().__init__()
    self.heads = nn.ModuleList([
      CausalAttention(din, dout, contextlen, dropout, bias) for _ in range(numheads)
    ])

  def forward(self, x):
    return torch.cat([h(x) for h in self.heads], dim=-1)

torch.manual_seed(1)
mulhattn = MultiHeadAttention(3, 3, 2, contextlen, 0.5)
print(mulhattn(batch))

tensor([[[ 0.0389, -0.0237,  0.0000,  0.0000, -1.1504, -0.3926],
         [-0.1063,  0.0422,  0.4604, -0.5220, -0.5139,  0.0286],
         [-0.1229,  0.0468,  0.3014, -0.3418, -0.6799,  0.0321],
         [-0.0924,  0.0333,  1.0543, -1.2263, -0.3786,  0.0467],
         [-0.0397,  0.0162,  0.6398, -0.8209, -0.4066,  0.0192],
         [-0.0847,  0.0348,  0.5932, -0.6752,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.9813, -1.1128,  0.0000,  0.0000],
         [-0.0866,  0.0302,  0.0000,  0.0000, -1.0882, -0.1674],
         [ 0.0000,  0.0000,  1.4225, -1.6550, -0.7192, -0.1170],
         [-0.0976,  0.0380,  0.6488, -0.7482, -0.3786,  0.0467],
         [ 0.0000,  0.0000,  0.5389, -0.6143, -0.1016,  0.0296],
         [ 0.0067, -0.0041,  0.9281, -1.0294, -0.3659, -0.0612]]],
       grad_fn=<CatBackward0>)


In [2]:
import torch
# (b, num_heads, num_tokens, head_dim) = (1, 2, 3, 4)
a = torch.tensor([[[[0.2745, 0.6584, 0.2775, 0.8573],
                    [0.8993, 0.0390, 0.9268, 0.7388],
                    [0.7179, 0.7058, 0.9156, 0.4340]],

                   [[0.0772, 0.3565, 0.1479, 0.5331],
                    [0.4066, 0.2318, 0.4545, 0.9737],
                    [0.4606, 0.5159, 0.4220, 0.5786]]]])

print(a @ a.transpose(2, 3))

tensor([[[[1.3208, 1.1631, 1.2879],
          [1.1631, 2.2150, 1.8424],
          [1.2879, 1.8424, 2.0402]],

         [[0.4391, 0.7003, 0.5903],
          [0.7003, 1.3737, 1.0620],
          [0.5903, 1.0620, 0.9912]]]])


In [4]:
print(a.shape[-1])

4


In [3]:
print(a @ a.transpose(-2, -1))

tensor([[[[1.3208, 1.1631, 1.2879],
          [1.1631, 2.2150, 1.8424],
          [1.2879, 1.8424, 2.0402]],

         [[0.4391, 0.7003, 0.5903],
          [0.7003, 1.3737, 1.0620],
          [0.5903, 1.0620, 0.9912]]]])


In [24]:
# more efficient way for multi-head attention
import torch.nn as nn
class MultiHeadAttentionV2(nn.Module):
  def __init__(self, numhead, din, dout, contextlen, dropout, bias = False):
    super().__init__()
    self.dout=dout
    assert(dout % numhead == 0)
    self.headdim = dout // numhead
    self.numhead = numhead

    self.queryW = nn.Linear(din, dout, bias)
    self.keyW = nn.Linear(din, dout, bias)
    self.valueW = nn.Linear(din, dout, bias)
    self.outproj = nn.Linear(dout, dout) # Linear layer to combine head outputs, can be removed in recent research
    self.dropout = nn.Dropout(dropout)
    self.register_buffer('mask', torch.triu(torch.ones(contextlen, contextlen), diagonal=1))


  def forward(self, x):
    b, numstoken, din = x.shape

    keys = self.keyW(x) #(b, numstoken, dout)
    # print("keys before unroll:", keys.shape, keys)
    queries = self.queryW(x)
    values = self.valueW(x)

    keys = keys.view(b, numstoken, self.numhead, self.headdim) #(b, numstoken, numhead, headdim)
    # print("keys after unroll:", keys.shape, keys)
    queries = queries.view(b, numstoken, self.numhead, self.headdim)
    values = values.view(b, numstoken, self.numhead, self.headdim)

    keys = keys.transpose(1, 2) #(b, numhead, numstoken, headdim)
    queries = queries.transpose(1, 2)
    values = values.transpose(1, 2)

    attScores = queries @ keys.transpose(2,3) # 2,2,6,1 * 2,2,1,6=>2,2,6,6
    # print("attScores", attScores.shape, attScores)
    attScores.masked_fill(self.mask.bool()[:numstoken, :numstoken], -torch.inf)

    attWeights = torch.softmax(attScores / self.headdim**0.5, dim=-1)
    # print("attWeights", attWeights.shape, attWeights)
    attWeights = self.dropout(attWeights)

    contextVectors = attWeights @ values # 2,2,6,6 * 2,2,6,1=>2,2,6,1
    contextVectors = contextVectors.transpose(1, 2) # (b, numstoken, numhead, headdim) 2,6,2,1
    contextVectors = contextVectors.contiguous().view(b, numstoken, self.dout)
    # contextVectors = contextVectors.reshape(b, numstoken, -1)
    context_vec = self.outproj(contextVectors)
    return context_vec



In [25]:
torch.manual_seed(1)
batchSize, contextlen, din = batch.shape
dout = 2
mulhattn = MultiHeadAttentionV2(2,din,dout,contextlen, 0.5)
contextVectors = mulhattn(batch)
print(contextVectors)

tensor([[[-0.1541, -0.2885],
         [-0.1894, -0.2814],
         [-0.1704, -0.2907],
         [-0.1093, -0.3168],
         [-0.1915, -0.2895],
         [-0.1205, -0.3202]],

        [[-0.1306, -0.3122],
         [-0.1862, -0.2963],
         [-0.1976, -0.2744],
         [-0.1286, -0.3099],
         [-0.1991, -0.2713],
         [-0.1703, -0.2929]]], grad_fn=<ViewBackward0>)
